version: '3.3'

services:
  covee:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    volumes:
      - ./:/covee
    stdin_open: true
    # command: tail -F dgrthetyj
    ports:
      - 7071:8000