version: '3.3'

services:
  covee:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    volumes:
      - ./:/covee
    stdin_open: true
    # command: tail -F dgrthetyj
    command: bash -c "cd covee &&
                      make init &&
                      python covee_main.py"
    ports:
      - 7071:8000