version: '3.3'

services:
  covee:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    networks:
      - covee-network
    volumes:
      - ./:/covee
      - ../packaging/DT:/covee/DT
      - ../profile_data/simulation:/covee/covee/powerflow/data/profiles/Test
      - ../profile_data/forecast:/covee/covee/control_strategies/forecast
      
    stdin_open: true
    command: bash -c "cd covee &&
                  python3 covee_main.py" 
    ports:
      - 9090:9090

networks:
  covee-network:
    external:
      name: covee-network