# Telegraf Agent Configuration
[agent]
  debug = true
  interval = "100ms"
  collection_jitter = "0s"
  flush_interval = "100ms"
  flush_jitter = "0s"

# Input Plugin Configuration
[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt:1883"]
  qos = 0
  connection_timeout = "2s"
  topics = ["measurements"]
  persistent_session = false
  data_format = "json"

# Output Plugin Configuration (InfluxDB v2)
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "iit2"
  bucket = "iit2"
